"""
Color configuration for the different parts of the application.
"""


class ElectrodeColors:
    HEADSCAN_LABELED_ELECTRODES_COLOR = "b7"
    HEADSCAN_UNLABELED_ELECTRODES_COLOR = "g7"

    MRI_LABELED_ELECTRODES_COLOR = "b7"
    MRI_UNLABELED_ELECTRODES_COLOR = "g7"

    LABELING_REFERENCE_ELECTRODES_COLOR = "y7"
    LABELING_MEASURED_UNLABELED_ELECTRODES_COLOR = "r7"
    LABELING_MEASURED_LABELED_ELECTRODES_COLOR = "b7"


class HeadModelColors:
    MRI_SURFACE_COLOR = (170, 170, 170)
    LABELING_SPHERE_COLOR = "#857c72"


HOUGH_CIRCLES_COLOR = (255, 0, 255)
