"""
Color configuration for the different parts of the application.
"""
class ElectrodeColors:
    HEADSCAN_LABELED_ELECTRODES_COLOR = "b5"
    HEADSCAN_UNLABELED_ELECTRODES_COLOR = "r5"
    
    MRI_LABELED_ELECTRODES_COLOR = "b8"
    MRI_UNLABELED_ELECTRODES_COLOR = "r8"

    LABELING_REFERENCE_ELECTRODES_COLOR = "#E64B01"
    LABELING_MEASURED_UNLABELED_ELECTRODES_COLOR = "#F0A503"
    LABELING_MEASURED_LABELED_ELECTRODES_COLOR = "#659C3C"
    
    
class HeadModelColors:
    MRI_SURFACE_COLOR = (170, 170, 170)
    LABELING_SPHERE_COLOR = "#857c72"
    
    

HOUGH_CIRCLES_COLOR = (255, 0, 255)